repos:
- repo: local
  hooks:
    # Run the ruff linter.
    - id: ruff-check
      name: ruff check
      language: system
      entry: uv run --frozen ruff check
      types_or: [python, pyi]
      args: [--fix]
      files: ^(src|tests)/
    # Run the ruff formatter.
    - id: ruff-format
      name: ruff format
      language: system
      entry: uv run --frozen ruff format
      types_or: [python, pyi]
      files: ^(src|tests)/
    - id: cython-lint
      name: cython-lint
      language: system
      entry: uv run --frozen cython-lint
      files: ^src/.*\.pyx?$