"""Particle status codes."""

from . cimport STATUS

STATUS_VALUES = {
    "INACTIVE": STATUS.INACTIVE,
    "NORMAL": STATUS.NORMAL,
    "NONFINITE": STATUS.NONFINITE,
    "OUT_OF_DOMAIN": STATUS.OUT_OF_DOMAIN,
    "BELOW_BOTTOM": STATUS.BELOW_BOTTOM,
    "ABOVE_SURFACE": STATUS.ABOVE_SURFACE,
    "MULTISTEP_1": STATUS.MULTISTEP_1,
    "MULTISTEP_2": STATUS.MULTISTEP_2,
    "PRE_RELEASE": STATUS.PRE_RELEASE,
    "POST_RETIREMENT": STATUS.POST_RETIREMENT,
}
